spring.application.name=catalog-service
server.port=8081
server.shutdown=graceful

#expose all endpoints of Actuator
management.endpoints.web.exposure.include=*
management.info.git.mode=full

catalog.page=10

# DB_URl -> take url from docker-compose file , if not present then run on local host , if present then run app in container
spring.datasource.url=${DB_URl:jdbc:postgresql://localhost:15432/postgres}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:Shivam@123}

