server:
  port: 8989
# this api gateway only delegates the requests to down stream services , we are not configuring rate limiting and other things .
spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: catalog-service
          uri: http://localhost:8081
          predicates:
            - Path=/catalog/**
          filters:
            - StripPrefix=1
        - id: orders-service
          uri: http://localhost:8082
          predicates:
            - Path=/orders/**
          filters:
            - StripPrefix=1

      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods: "*"
            allowed-headers: "*"

management:
  endpoints:
    web:
      exposure:
        include: "*"

# we can configure it dynamically
springdoc:
  swagger-ui:
    use-root-path: true
    urls:  # drop down for services
      - name: catalog
        url: /catalog/v3/api-docs
      - name: orders
        url: /orders/v3/api-docs