version: "3.8"
name: 'book-store'
services:
  catalog-db:
    image: postgres:16-alpine
    container_name: catalog-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Shivam@123
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    #left host port , right container port

    healthcheck:
      test: [ "CMD-SHELL", "pg isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 500m
